[package]
name = "rumi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p256 = { version = "0.13.2", features = ["hash2curve", "serde"] }
rand = "0.8.5"
sha2 = { version = "0.10.8", features = ["asm"] }
uuid = { version = "1.5.0", features = ["std", "v4"] }
blake3 = "1.3.1"
zeroize = { version = "1.5.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
ark-ff = "0.4.2"
ark-bls12-381 = "0.4.0"
generic-array = "0.14.7"