version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    networks:
      - rumi-net
      - monitoring_monitoring  # To connect with monitoring stack

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - rumi-net
    command: ["lookup", "1000000042"]  # Example command, can be overridden

networks:
  rumi-net:
    driver: bridge
  monitoring_monitoring:
    external: true  # Connect to monitoring network 