ARG RUST_VERSION=1.75.0
FROM rust:${RUST_VERSION}-slim-bookworm as builder

WORKDIR /usr/src/rumi
COPY . .
RUN cargo build --release --bin client

FROM debian:bookworm-slim

COPY --from=builder /usr/src/rumi/target/release/client /usr/local/bin/
ENTRYPOINT ["client"] 