ARG RUST_VERSION=1.75.0
FROM rust:${RUST_VERSION}-slim-bookworm as builder

WORKDIR /usr/src/rumi
COPY . .
RUN cargo build --release --bin server

FROM debian:bookworm-slim

COPY --from=builder /usr/src/rumi/target/release/server /usr/local/bin/
CMD ["server"] 