FROM rust:1.74-slim as builder

WORKDIR /usr/src/rumi
COPY . .
RUN cargo build --release --bin server

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/rumi/target/release/server /usr/local/bin/server

EXPOSE 50051
CMD ["server"] 